### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by ghost** [nmajor25/seconds-converter#3]
Hey great module !!
I see a pull request for a type error.
but when i installed the package ^1.3.0 
the type error is still there. 

I had to go in the module package to 
escape the 'sec' and 'ms'.

**Comment by AlooAkbar** [comment]
Same here @Gyzimo

**Comment by MoonLGH** [comment]
that just the lib error
open 
node_modules => second-converter => index.js

change
throw new TypeError('Unit must be 'sec' or 'ms'')
to
   throw new TypeError("Unit must be 'sec' or 'ms'")
